<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="HL7SoapMsgs" targetNamespace="http://www.example.org/HL7SoapMsgs/" xmlns:sns="http:///HL7Services/HL7SoapSchemas.xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/HL7SoapMsgs/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="HL7SoapMsgsSOAP" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.example.org/HL7SoapMsgs/">
<xsd:import namespace="http:///HL7Services/HL7SoapSchemas.xsd" schemaLocation="HL7SoapSchemas.xsd"/>
</xsd:schema>
  </wsdl:types>
  <wsdl:message name="HL7SoapReq">
    <wsdl:part element="sns:HL7ReqType" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="HL7SoapResp">
    <wsdl:part element="sns:HL7RespType" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="HL7SoapMsgs">
    <wsdl:operation name="NewOperation">
      <wsdl:input message="tns:HL7SoapReq"/>
      <wsdl:output message="tns:HL7SoapResp"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="HL7SoapMsgsSOAP" type="tns:HL7SoapMsgs">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="NewOperation">
      <soap:operation soapAction="http://www.example.org/HL7SoapMsgs/NewOperation"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HL7SoapMsgs">
    <wsdl:port binding="tns:HL7SoapMsgsSOAP" name="HL7SoapMsgsSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>